import type { Task } from '../../../types/task';

export const mockTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Design Dashboard Wireframes',
    description: 'Create high-fidelity landing page and grid dashboard wireframes on Figma for review.',
    assignedTo: 'Rahul Dev',
    status: 'Completed',
    priority: 'High',
    dueDate: '2026-06-19',
    createdAt: '2026-06-16T09:00:00Z',
  },
  {
    id: 'task-2',
    title: 'Initialize Git & Scaffold Vite',
    description: 'Set up Vite React template, TypeScript support, and strict configuration parameters.',
    assignedTo: 'Amit Kumar',
    status: 'Completed',
    priority: 'Medium',
    dueDate: '2026-06-20',
    createdAt: '2026-06-16T10:30:00Z',
  },
  {
    id: 'task-3',
    title: 'Configure Tailwind CSS',
    description: 'Integrate Tailwind CSS v4 directives, color systems, and load Outfit and Inter fonts.',
    assignedTo: 'Rahul Dev',
    status: 'Completed',
    priority: 'High',
    dueDate: '2026-06-21',
    createdAt: '2026-06-17T11:00:00Z',
  },
  {
    id: 'task-4',
    title: 'Build Responsive Sidebar Shell',
    description: 'Implement responsive shell grid, top navigation header, sidebar options and mobile support.',
    assignedTo: 'Priya Sharma',
    status: 'In Progress',
    priority: 'Medium',
    dueDate: '2026-06-22',
    createdAt: '2026-06-17T11:15:00Z',
  },
  {
    id: 'task-5',
    title: 'Create Task Mock Database',
    description: 'Establish standard Task JSON schemas and create realistic mock records for local testing.',
    assignedTo: 'Amit Kumar',
    status: 'Pending',
    priority: 'Low',
    dueDate: '2026-06-23',
    createdAt: '2026-06-18T09:00:00Z',
  },
  {
    id: 'task-6',
    title: 'Design Filter & Search Inputs',
    description: 'Implement TaskFilters component container, SearchInput and SelectFilter dropdown UI elements.',
    assignedTo: 'Priya Sharma',
    status: 'Pending',
    priority: 'High',
    dueDate: '2026-06-24',
    createdAt: '2026-06-18T10:30:00Z',
  },
  {
    id: 'task-7',
    title: 'Integrate State CRUD Actions',
    description: 'Implement task modal, validation, create task form, edit task and delete confirmation dialogs.',
    assignedTo: 'Rahul Dev',
    status: 'In Progress',
    priority: 'High',
    dueDate: '2026-06-25',
    createdAt: '2026-06-19T09:00:00Z',
  },
  {
    id: 'task-8',
    title: 'Set up SQLite Backend API',
    description: 'Initialize Next.js API server, create database models with Prisma ORM, and configure controllers.',
    assignedTo: 'Amit Kumar',
    status: 'Cancelled',
    priority: 'Low',
    dueDate: '2026-06-26',
    createdAt: '2026-06-19T11:00:00Z',
  },
  {
    id: 'task-9',
    title: 'Write Unit Tests for Components',
    description: 'Add Vitest tests for TaskTable, TaskForm, and dashboard chart components.',
    assignedTo: 'Priya Sharma',
    status: 'Pending',
    priority: 'Medium',
    dueDate: '2026-06-27',
    createdAt: '2026-06-20T10:00:00Z',
  },
  {
    id: 'task-10',
    title: 'Implement Theme Switching',
    description: 'Add light/dark theme toggle with localStorage persistence and time-based auto dark mode.',
    assignedTo: 'Rahul Dev',
    status: 'Completed',
    priority: 'High',
    dueDate: '2026-06-28',
    createdAt: '2026-06-21T09:30:00Z',
  },
  {
    id: 'task-11',
    title: 'Optimize Chart Rendering',
    description: 'Refine Recharts responsive containers and reduce unnecessary re-renders on data updates.',
    assignedTo: 'Amit Kumar',
    status: 'In Progress',
    priority: 'Medium',
    dueDate: '2026-06-29',
    createdAt: '2026-06-22T08:00:00Z',
  },
  {
    id: 'task-12',
    title: 'Prepare Deployment Checklist',
    description: 'Document build steps, environment variables, and verification checklist for production release.',
    assignedTo: 'Priya Sharma',
    status: 'Pending',
    priority: 'Low',
    dueDate: '2026-06-30',
    createdAt: '2026-06-22T14:00:00Z',
  },
];
